name: Bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  bazel:
    name: Bazel
    runs-on: macos-13
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Build
      run: bazelisk build --noenable_bzlmod //:all
