name: CocoaPods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  cocoapods:
    name: CocoaPods
    runs-on: macos-13
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Lint
      run: pod lib lint --skip-tests --verbose Layout.podspec
